[package]
name = "othello-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.25.0"
rand = "0.8.5"
tungstenite = "0.18.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
url = "2.3.1"
reqwest = { version = "0.11.13", features = ["blocking", "json"] }